@startuml

left to right direction

abstract class ee.ria.DigiDoc.idcard.PersonalData
abstract class ee.ria.DigiDoc.smartcardreader.SmartCardReader
class ee.ria.DigiDoc.idcard.CodeVerificationException
class ee.ria.DigiDoc.idcard.IdCardException
class ee.ria.DigiDoc.idcard.Idemia
class ee.ria.DigiDoc.idcard.IdemiaPersonalDataParser
class ee.ria.DigiDoc.idcard.IdemiaWithPace
class ee.ria.DigiDoc.idcard.PaceTunnelException
class ee.ria.DigiDoc.idcard.Thales
class ee.ria.DigiDoc.idcard.ThalesPersonalDataParser
class ee.ria.DigiDoc.idcard.ThalesWithPace
class ee.ria.DigiDoc.smartcardreader.ApduResponseException
class ee.ria.DigiDoc.smartcardreader.SmartCardReaderException
class ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReader


package "java" as java <<External>>{
  package io {}
  package math {}
  package nio {}
  package security {}
  package time {}
  package util {}
}

package "javax" as javax <<External>> {
  package crypto {}
}

package org.bouncycastle <<External>> {
  package crypto {}
  package jce {}
  package math {}
  package util {}
}

enum ee.ria.DigiDoc.idcard.CardType
enum ee.ria.DigiDoc.idcard.CertificateType
enum ee.ria.DigiDoc.idcard.CodeType
interface ee.ria.DigiDoc.idcard.Token
interface ee.ria.DigiDoc.idcard.TokenWithPace
interface ee.ria.DigiDoc.smartcardreader.nfc.ApduEncryptor


ee.ria.DigiDoc.idcard.Thales -up-|> ee.ria.DigiDoc.idcard.Token
ee.ria.DigiDoc.idcard.Thales ..> ee.ria.DigiDoc.smartcardreader.SmartCardReader
ee.ria.DigiDoc.idcard.Thales ..> ee.ria.DigiDoc.idcard.ThalesPersonalDataParser
ee.ria.DigiDoc.idcard.ThalesWithPace -up-|> ee.ria.DigiDoc.idcard.Thales
ee.ria.DigiDoc.idcard.ThalesWithPace -up-|> ee.ria.DigiDoc.idcard.TokenWithPace
ee.ria.DigiDoc.idcard.ThalesWithPace -up-|> ee.ria.DigiDoc.smartcardreader.nfc.ApduEncryptor
ee.ria.DigiDoc.idcard.ThalesWithPace ..> ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReader
ee.ria.DigiDoc.idcard.Idemia -up-|> ee.ria.DigiDoc.idcard.Token
ee.ria.DigiDoc.idcard.Idemia ..> ee.ria.DigiDoc.smartcardreader.SmartCardReader
ee.ria.DigiDoc.idcard.Idemia ..> ee.ria.DigiDoc.idcard.IdemiaPersonalDataParser
ee.ria.DigiDoc.idcard.IdemiaWithPace -up-|> ee.ria.DigiDoc.idcard.Idemia
ee.ria.DigiDoc.idcard.IdemiaWithPace -up-|> ee.ria.DigiDoc.idcard.TokenWithPace
ee.ria.DigiDoc.idcard.IdemiaWithPace -up-|> ee.ria.DigiDoc.smartcardreader.nfc.ApduEncryptor
ee.ria.DigiDoc.idcard.IdemiaWithPace ..> ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReader
ee.ria.DigiDoc.idcard.Token ..> ee.ria.DigiDoc.smartcardreader.SmartCardReader
ee.ria.DigiDoc.idcard.TokenWithPace ..> ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReader
ee.ria.DigiDoc.idcard.TokenWithPace -up-|> ee.ria.DigiDoc.idcard.Token
ee.ria.DigiDoc.idcard.PersonalData ..> ee.ria.DigiDoc.idcard.CardType
@enduml
