@startuml


left to right direction

package ee.ria.DigiDoc.idcard {}
abstract class ee.ria.DigiDoc.smartcardreader.SmartCardReader

class ee.ria.DigiDoc.smartcardreader.ApduResponseException
class ee.ria.DigiDoc.smartcardreader.SmartCardReaderException
class ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReader
class ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReaderManager

package java <<External>> {
  package io {}
  package security {}
  package util {}
}

package org.bouncycastle <<External>> {
  package util {}
}

package "nfc" as ee.ria.DigiDoc.smartcardreader.nfc.android.nfc <<External>> {
  class Tag
  class tech.IsoDep
  interface NfcAdapter.ReaderCallback
}

package "android" as ee.ria.DigiDoc.smartcardreader.android <<External>> {
  class app.Activity
}

interface ee.ria.DigiDoc.smartcardreader.nfc.ApduEncryptor
ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReader -up-|> ee.ria.DigiDoc.smartcardreader.SmartCardReader
ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReader ..> ee.ria.DigiDoc.smartcardreader.nfc.android.nfc.Tag
ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReader ..> ee.ria.DigiDoc.smartcardreader.nfc.android.nfc.tech.IsoDep
ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReaderManager ..> ee.ria.DigiDoc.smartcardreader.android.app.Activity
ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReaderManager ..> ee.ria.DigiDoc.smartcardreader.nfc.android.nfc.NfcAdapter
ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReaderManager ..> ee.ria.DigiDoc.smartcardreader.nfc.android.nfc.Tag
ee.ria.DigiDoc.smartcardreader.nfc.NfcSmartCardReaderManager -up-|> ee.ria.DigiDoc.smartcardreader.nfc.android.nfc.NfcAdapter.ReaderCallback
@enduml
